/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ATraktorRouteImport } from './routes/a-traktor'
import { Route as DepaRouteImport } from './routes/depa'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as OffertRouteImport } from './routes/offert'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ATraktorRoute = ATraktorRouteImport.update({
  id: '/a-traktor',
  path: '/a-traktor',
  getParentRoute: () => rootRouteImport,
} as any)
const DepaRoute = DepaRouteImport.update({
  id: '/depa',
  path: '/depa',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const OffertRoute = OffertRouteImport.update({
  id: '/offert',
  path: '/offert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-traktor': typeof ATraktorRoute
  '/depa': typeof DepaRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-traktor': typeof ATraktorRoute
  '/depa': typeof DepaRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-traktor': typeof ATraktorRoute
  '/depa': typeof DepaRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/kontakt': typeof KontaktRoute
  '/offert': typeof OffertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/a-traktor' | '/depa' | '/integritetspolicy' | '/kontakt' | '/offert'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/a-traktor' | '/depa' | '/integritetspolicy' | '/kontakt' | '/offert'
  id:
    | '__root__'
    | '/'
    | '/a-traktor'
    | '/depa'
    | '/integritetspolicy'
    | '/kontakt'
    | '/offert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ATraktorRoute: typeof ATraktorRoute
  DepaRoute: typeof DepaRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  KontaktRoute: typeof KontaktRoute
  OffertRoute: typeof OffertRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-traktor': {
      id: '/a-traktor'
      path: '/a-traktor'
      fullPath: '/a-traktor'
      preLoaderRoute: typeof ATraktorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/depa': {
      id: '/depa'
      path: '/depa'
      fullPath: '/depa'
      preLoaderRoute: typeof DepaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offert': {
      id: '/offert'
      path: '/offert'
      fullPath: '/offert'
      preLoaderRoute: typeof OffertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ATraktorRoute: ATraktorRoute,
  DepaRoute: DepaRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  KontaktRoute: KontaktRoute,
  OffertRoute: OffertRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
